name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  extract-version:
    name: extract-version
    runs-on: ubuntu-latest
    outputs:
      cocmd_version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: "Extract version"
        id: "version"
        run: |
          COCMD_VERSION=$(grep '^version' Cargo.toml | awk -F '"' '{ print $2 }')
          echo version: $COCMD_VERSION
          echo "::set-output name=version::v$COCMD_VERSION"

  publish:
    name: Publishing for ${{ matrix.os }}
    needs: ["extract-version"]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin, x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl, i686-unknown-linux-gnu, aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf, arm-unknown-linux-gnueabi, x86_64-pc-windows-msvc]
        rust: [stable]
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_postfix: ""
          - os: macos-latest
            target: aarch64-apple-darwin
            binary_postfix: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_postfix: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            binary_postfix: ""
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            binary_postfix: ""
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            binary_postfix: ""
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            binary_postfix: ""
          - os: ubuntu-latest
            target: arm-unknown-linux-gnueabi
            binary_postfix: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_postfix: ".exe"
    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
          target: ${{ matrix.target }}
      - name: Setup MUSL
        if: matrix.os == 'ubuntu-latest'
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get update
          sudo apt-get install musl-tools

      - name: Setup ARM toolchain
        if: matrix.os == 'ubuntu-latest'
        run: |
          rustup target add aarch64-unknown-linux-gnu
          rustup target add armv7-unknown-linux-gnueabihf
          rustup target add arm-unknown-linux-gnueabihf

          curl -o $GITHUB_WORKSPACE/aarch64.tar.xz https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-a/8.2-2018.08/gcc-arm-8.2-2018.08-x86_64-aarch64-linux-gnu.tar.xz
          curl -o $GITHUB_WORKSPACE/arm.tar.xz https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-a/8.2-2018.08/gcc-arm-8.2-2018.08-x86_64-arm-linux-gnueabihf.tar.xz

          tar xf $GITHUB_WORKSPACE/aarch64.tar.xz
          tar xf $GITHUB_WORKSPACE/arm.tar.xz

          echo "$GITHUB_WORKSPACE/gcc-arm-8.2-2018.08-x86_64-aarch64-linux-gnu/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/gcc-arm-8.2-2018.08-x86_64-arm-linux-gnueabihf/bin" >> $GITHUB_PATH
      
      - name: Installing needed macOS dependencies
        if: matrix.os == 'macos-latest'
        run: brew install openssl@1.1
      - name: Installing needed Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu gcc-mingw-w64-x86-64
      - name: Checking out sources
        uses: actions/checkout@v1
      - name: Running cargo build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          toolchain: ${{ matrix.rust }}
          args: --release --target ${{ matrix.target }} -p cocmd

      - name: Packaging final binary
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release

          BINARY_NAME=cocmd${{ matrix.binary_postfix }}

          RELEASE_NAME=cocmd-${{ matrix.target }}
          tar czvf $RELEASE_NAME.tar.gz $BINARY_NAME

          if [[ ${{ runner.os }} == 'Windows' ]]; then
            certutil -hashfile $RELEASE_NAME.tar.gz sha256 | grep -E [A-Fa-f0-9]{64} > $RELEASE_NAME.sha256
          else
            shasum -a 256 $RELEASE_NAME.tar.gz > $RELEASE_NAME.sha256
          fi
      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release/cocmd-${{ matrix.target }}.tar.gz
            target/${{ matrix.target }}/release/cocmd-${{ matrix.target }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-cargo:
    name: Publishing to Cargo
    needs: ["extract-version"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: |
          sudo apt-get update
          sudo apt-get install -y -qq pkg-config libssl-dev libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CARGO_API_KEY }} --allow-dirty -p cocmd
  

  macos-publish-homebrew:
    needs: ["extract-version"]
    runs-on: macos-11
  
    steps:
      - uses: actions/checkout@v2
  
      - name: Print target version
        run: |
          echo Using version ${{ needs.extract-version.outputs.cocmd_version }}
  
      - name: "Setup SSH deploy key"
        uses: webfactory/ssh-agent@fc49353b67b2b7c1e0e6a600572d01a69f2672dd
        with:
          ssh-private-key: ${{ secrets.HOMEBREW_CASK_SSH_PRIVATE_KEY }}
      
      - name: Create and Publish Homebrew Cask
        run: |
          VERSION="${{ needs.extract-version.outputs.cocmd_version }}" ./.github/scripts/publish_homebrew_version.sh
  
  snap-build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
          - s390x
          - ppc64el
          - arm64
          - armhf
          - amd64
          - i386
    steps:
    - uses: actions/checkout@v2
    - name: Modify snapcraft.yaml
      run: |
        sed -i "s/run-on: \[CHANGE_ME\]/run-on: \[${{ matrix.architecture }}\]/" snapcraft.yaml

    - uses: snapcore/action-build@v1
      id: build
    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_LOGIN }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: stable
        
  update-website:
    needs: ["extract-version", "publish", "macos-publish-homebrew", "snap-build-publish"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Print target version
        run: |
          echo Using version ${{ needs.extract-version.outputs.cocmd_version }}

      - name: "Setup SSH deploy key"
        uses: webfactory/ssh-agent@fc49353b67b2b7c1e0e6a600572d01a69f2672dd
        with:
          ssh-private-key: ${{ secrets.COCMD_WEBSITE_SSH_PRIVATE_KEY }}
      - name: git config
        run: |
          git config --global user.email "cocmd@cocmd.org"
          git config --global user.name "Github Actions"

      - name: install latest cocmd
        uses: actions-rs/cargo@v1
        with:
          command: install
          toolchain: stable
          args: --path .

      - name: Update version in website
        run: |
          VERSION="${{ needs.extract-version.outputs.cocmd_version }}" ./.github/scripts/publish_website_version.sh
      
        